apiVersion: v1
kind: PersistentVolume
metadata:
  name: tasks-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: standard
  hostPath:
    path: /tasks
    type: DirectoryOrCreate
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tasks-pvc
spec:
  volumeName: tasks-pv
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
